### ISSUE TITLE
Holding/releasing left+right mouse buttons should auto-click adjacent squares

### ISSUE THREAD

**Issue by alexqfredrickson** [1000hz/winmine-exe#5]
Just a nice-to-have 😄😄 

["If all the mines touching a number are flagged, you can press both buttons on that number to clear the remaining adjacent squares." 
](http://www.minesweeper.info/wiki/Windows_Minesweeper)

**Comment by 1000hz** [comment]
This is something I've been wanting to implement for the longest time, but it required refactoring the way pressed square styles get applied since the current way relied on `:active`/`:hover` selectors on individual squares but chording needs all surrounding squares to get pressed as well. Finally got around to it. Thanks for the nudge!
